/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MoneyMuleFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MoneyMuleFactory__factory>
getContractFactory(name: 'MoneyMuleRound', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MoneyMuleRound__factory>
getContractFactory(name: 'USDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.USDC__factory>

  getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MoneyMuleFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MoneyMuleFactory>
getContractAt(name: 'MoneyMuleRound', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MoneyMuleRound>
getContractAt(name: 'USDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.USDC>

  deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MoneyMuleFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MoneyMuleFactory>
deployContract(name: 'MoneyMuleRound', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MoneyMuleRound>
deployContract(name: 'USDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDC>

  deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MoneyMuleFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MoneyMuleFactory>
deployContract(name: 'MoneyMuleRound', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MoneyMuleRound>
deployContract(name: 'USDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  