/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as moneyMuleSol from './MoneyMule.sol/index.js';
export type { moneyMuleSol };
import type * as usdcSol from './USDC.sol/index.js';
export type { usdcSol };
export * as factories from './factories/index.js';
export type { MoneyMule } from './MoneyMule.sol/MoneyMule.js';
export { MoneyMule__factory } from './factories/MoneyMule.sol/MoneyMule__factory.js';
export type { USDC } from './USDC.sol/USDC.js';
export { USDC__factory } from './factories/USDC.sol/USDC__factory.js';